import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { BreadCrump1, BreadCrump2 } from '@/component/breadcrump'
import { headers } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const head = headers()
  const url = head.get('referer')!
  
  return (
    <html lang="en">
      <body className={ inter.className }>
        <div className="w-1/2 h-1/2">
          <section>
            Root layout
            <Link href="/">Go to /</Link>
            <Link href="/page1">Go to /page1</Link>
            <Link href="/page2">Go to /page2</Link>
          </section>
          <section>
            <BreadCrump1 />
          </section>
          <section>
            <BreadCrump2 url={url} />
          </section>
          { children }
        </div>
      </body>
    </html>
  )
}
