import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import GenerateLinks from './client'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    
  
  return (
    <html lang="en">
      <body className={ inter.className }>
        <Link href="/100">Go to Page 100 (server Link)</Link>
        <Link href="/200">Go to Page 200 (server Link)</Link>
        {/* <GenerateLinks /> */}
        { children }
      </body>
    </html>
  )
}
