import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import GenerateLinks from './client'
import Timer from '@/components/client'
import { cache } from 'react'
import { addGlobal, getRandomNumber } from '@/components/server'

const inter = Inter({
  subsets: ['latin'],
  display: 'optional'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  await new Promise((res) => setTimeout(res, 100))


  return (
    <html lang="en">
      <body className={ inter.className }>
        <section className="layout root">
          <p>{ Math.random() } | Cached: { getRandomNumber() } | GC: { addGlobal() }</p>
          <Timer />
          <Link href="/">Home</Link>
          <Link href="/100">Page [100]</Link>
          <Link href="/200">Page [200]</Link>
          <Link href="/apple">Apple</Link>
          <Link href="/banana">Banana</Link>
          <section className="children">
            { children }
          </section>
        </section>
      </body>
    </html>
  )
}


